service: orangejellyfish-serverless-starter
frameworkVersion: '=1.60.5'

provider:
  name: aws
  runtime: nodejs12.x

# Lambda function definitions. Each function defines itself in a separate YAML
# file that resides alongside the function implementation. Unfortunately we have
# to duplicate the function name here due to the way Serverless YAML importing
# and parsing works (in an ideal world we could include these in a list as we do
# for resources).
functions:
  hello: ${file(src/functions/hello/index.yml):hello}

# Custom AWS resource definitions. This includes anything that the Serverless
# framework doesn't handle for us, such as database setup, and overrides of
# Serverless defaults.
resources:
  - ${file(src/resources/apigateway.yml)}
  - ${file(src/resources/iam.yml)}

# Custom variables. These are mostly used to configure plugins.
custom:
  splitStacks:
    perFunction: true
    perType: false

# Serverless plugins. The "stage-variables" plugin is required to allow us to
# customise the API Gateway stage that gets created automatically by Serverless.
# The "split-stacks" plugin is used to generate nested CloudFormation stacks to
# avoid the hard limit of 200 resources per stack which is possible to hit over
# time with a relatively large service.
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-split-stacks
  - serverless-iam-roles-per-function
  - serverless-plugin-stage-variables
