service: orangejellyfish-serverless-starter
frameworkVersion: '=1.30.0'

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: src/functions/hello/index.default
    events:
      - http:
          path: hello
          method: get
      - schedule:
          rate: rate(5 minutes)
          enabled: true

custom:
  webpack:
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline
